kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-stateful-redis-2
spec:
  storageClassName: redis-manual-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200m