kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-stateful-redis-3
spec:
  storageClassName: redis-manual-3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200m