kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-5
  labels:
    type: local
spec:
  storageClassName: redis-manual-5
  capacity:
    storage: 200m
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /code/redis_path/n6